NERDBLOCK/config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/genres/new', to: 'genres#new'
  post '/genres/new',   to: 'genres#create'
  get	 '/subscriptions',    to: 'subscriptions#index'
  get  '/genres',           to: 'genres#index'
  post	 '/genres/:id',    to: 'subscriptions#create'
  post '/items/:id/edit', to: 'items#update'
  get '/items/new', to: 'items#new'
  post '/items/new',   to: 'items#create'
  post '/genres/:id/edit', to: 'genres#update'

  resources :users
  resources :subscriptions
  resources :genres
  resources :items
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

NERDBLOCK/app/models/item.rb
class Item < ApplicationRecord
end

NERDBLOCK/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
      @items = Item.all
  end

  def show
		@item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def edit
      @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
        redirect_to items_url
    else
      render 'new'
    end
  end

  def update
      @item = Item.find(params[:id])

      if @item.update_attributes(item_params)
          flash[:success] = "Item updated"
          redirect_to items_url
      else
          render 'edit'
      end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
                params.permit(:item_name, :genre_id, :item_description, :item_price)
    end
end

NERDBLOCK/app/helpers/items_helper.rb
module ItemsHelper
end

NERDBLOCK/app/views/items/_form.html.erb
<%= form_with(model: @items, local: true) do |form| %>

    <%= form.label :item_id%>
    <%= form.text_field :item_name, value: @item.item_name, class: 'form-control' %>
    <%= form.label :item_description %>
    <%= form.text_field :item_description, value: @item.item_description, class: 'form-control' %>
    <%= form.label :item_price %>
    <%= form.text_field :item_price, value: @item.item_price, class: 'form-control' %>

    <%= form.select :genre_id,
                  options_from_collection_for_select(Genre.all, "id", "genre_name", @item.genre_id)%>
    <%= form.submit yield(:button_text), class: "btn btn-primary" %>

<% end %>

NERDBLOCK/app/views/items/_item.html.erb
<tr>
  <td>
    <br />
  </td>
</tr>

<tr class="items">

    <tr>
        <td>
            Name: <%= item.item_name %><br>
        </td>
        <td>
            Description: <%= item.item_description %><br>
        </td>
        <td>
            Individual Cost: $<%= item.item_price %><br>
        </td>
        <td>
        <% if current_user.userType == "A" || current_user.userType == "S"%>
        <%= link_to "edit", edit_item_path(item) %>
        <% end %>
        <% if current_user.userType == "A" || current_user.userType == "S"%>
            <%= link_to "delete", item, method: :delete,
                                        data: { confirm: "You sure?" } %>
        <% end %>
    </tr>
    <tr>
      <td colspan=2>
        <hr />
      </td>

    </tr>

</tr>

NERDBLOCK/app/views/items/edit.html.erb
<% provide(:title, 'Edit item') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update item</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>

  </div>
</div>

NERDBLOCK/app/views/items/index.html.erb
<% provide(:title, 'Items') %>
<% provide(:button_text, 'Create new item') %>
<h1>All items</h1>

<% if current_user.userType == "A" || current_user.userType == "S"%>
<%= link_to "Create new item", items_new_path %>
<% end %>

<ul class="items">
  <%= render @items %>
</ul>

NERDBLOCK/app/views/items/new.html.erb
<% provide(:title, 'New Item') %>
<% provide(:button_text, 'Create new Item') %>
<h1>New Item</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

NERDBLOCK/app/views/items/show.html.erb
<% provide(:title, @item.item_name) %>
<% provide(:button_text, 'Subscribe') %>
<div class="row">
    <aside class="col-md-4">
        <section class="item-info">
            <h1>
                Item:
            </h1>
            <%= @item.item_name %><br />

            <h1>
                Description:
            </h1>
            <%= @item.item_description %><br />

            <h1>
                Individual Price:
            </h1>
            <%= @item.item_price %><br />

            <%= render 'form' %>
        </section>
    </aside>
</div>