NERDBLOCK/config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/genres/new', to: 'genres#new'
  post '/genres/new',   to: 'genres#create'
  get	 '/subscriptions',    to: 'subscriptions#index'
  get  '/genres',           to: 'genres#index'
  post	 '/genres/:id',    to: 'subscriptions#create'
  post '/items/:id/edit', to: 'items#update'
  get '/items/new', to: 'items#new'
  post '/items/new',   to: 'items#create'
  post '/genres/:id/edit', to: 'genres#update'

  resources :users
  resources :subscriptions
  resources :genres
  resources :items
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

NERDBLOCK/app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        NERDBLOCK &#169 Dec 2017
    </small>
    <nav>
        <ul>
            <li><%= link_to "About",   'about' %></li>
            <li><%= link_to "Contact", 'contact' %></li>
        </ul>
    </nav>
</footer>

NERDBLOCK/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "NERDBLOCK", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <% if (current_user.userType == "A" || current_user.userType=="S")%>
            <li><%= link_to "Items", items_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Subscriptions <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Subscriptions", subscriptions_path %></li>
              <li><%= link_to "Browse NERDBLOCKS", genres_path %></li>
              <li><%= link_to "Fee Statement", fee_statement %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

NERDBLOCK/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

NERDBLOCK/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:title)) %></title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all',
                                   'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application',
                                   'data-turbolinks-track': 'reload' %>
        <%= render 'layouts/shim' %>
    </head>

    <body>
        <%= render 'layouts/header' %>
        <div class="container">
            <% flash.each do |message_type, message| %>
                <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
            <% end %>

            <%= yield %>
            <%= render 'layouts/footer' %>
            <%= debug(params) if Rails.env.development? %>
        </div>
    </body>
</html>