NERDBLOCK/config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/genres/new', to: 'genres#new'
  post '/genres/new',   to: 'genres#create'
  get	 '/subscriptions',    to: 'subscriptions#index'
  get  '/genres',           to: 'genres#index'
  post	 '/genres/:id',    to: 'subscriptions#create'
  post '/items/:id/edit', to: 'items#update'
  get '/items/new', to: 'items#new'
  post '/items/new',   to: 'items#create'
  post '/genres/:id/edit', to: 'genres#update'

  resources :users
  resources :subscriptions
  resources :genres
  resources :items
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

NERDBLOCK/app/models/genre.rb
class Genre < ApplicationRecord
end

NERDBLOCK/app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
    @genres = Genre.find(params[:id])
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
        params.permit(:genre_name, :genre_description)
    end
end

NERDBLOCK/app/helpers/genres_helper.rb
module GenresHelper
end

NERDBLOCK/app/views/genres/_form.html.erb
<%= form_with(model: @subscriptions, local: true) do |form| %>

  <%= form.hidden_field :user_id, :value => current_user.id %>
  <%= form.hidden_field :genre_id, :value => @genre.id %>
  <%= form.hidden_field :start_date, :value => Time.now() %>
  <%= form.select :option_id,
                options_from_collection_for_select(SubscriptionOption.all, "id", "subscription_length", 1)%>
  <%= form.submit yield(:button_text), class: "btn btn-primary" %>

 <%= form.hidden_field :end_date, :value => Time.now() %>

<% end %>

NERDBLOCK/app/views/genres/_genre.html.erb
<tr>
  <td>
    <br />
  </td>
</tr>

<tr class="items">

    <tr>
        <td>
            Name: <%= genre.genre_name %><br>
        </td>
        <td>
            Description: <%= genre.genre_description %><br>
        </td>
        <td>
        <% if current_user.userType == "A" || current_user.userType == "S"%>
        <%= link_to "edit", edit_genre_path(genre) %>
        <% end %>
        <% if current_user.userType == "A" || current_user.userType == "S"%>
            <%= link_to "delete", genre, method: :delete,
                                        data: { confirm: "You sure?" } %>
        <% end %>
    </tr>
    <tr>
      <td colspan=2>
        <hr />
      </td>

    </tr>

</tr>

NERDBLOCK/app/views/genres/_item.html.erb
<tr>
  <td>
    <br />
  </td>
</tr>

<tr class="items">

  <td>

  <%  items = Item.where(:genre_id => @genre.id).select("item_name")%>
  <% items.each do |item| %>
    <%= item.item_name %><br>
  <% end %>
  </td>
</tr>

NERDBLOCK/app/views/genres/_newForm.html.erb
<%= form_with(model: @genres, local: true) do |form| %>

<%= form.label :genre_name%>
<%= form.text_field :genre_name, value: @genre.genre_name, class: 'form-control' %>
<%= form.label :genre_description %>
<%= form.text_field :genre_description, value: @genre.genre_description, class: 'form-control' %>

<%= form.submit yield(:button_text), class: "btn btn-primary" %>

<% end %>

NERDBLOCK/app/views/genres/edit.html.erb
<% provide(:title, 'Edit item') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update item</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'newForm' %>

  </div>
</div>
<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

NERDBLOCK/app/views/genres/index.html.erb
<% provide(:title, 'Genres') %>
<h1>All NERDBLOCK genres</h1>
<% provide(:button_text, 'Create new NERDBLOCK Genre') %>

<% if current_user.userType == "A" || current_user.userType == "S"%>
<%= link_to "Create new NERDBLOCK Genre", genres_new_path %>
<% end %>

<ul class="genres">
  <%= render @genres %>
</ul>

NERDBLOCK/app/views/genres/new.html.erb
<h1>New Genre</h1>
<% provide(:button_text, 'Create new NERDBLOCK Genre') %>
<%= render 'newForm', genre: @genre %>

<%= link_to 'Back', genres_path %>

NERDBLOCK/app/views/genres/show.html.erb
<% provide(:title, @genre.genre_name) %>
<% provide(:button_text, 'Subscribe') %>
<div class="row">
    <aside class="col-md-4">
        <section class="genre-info">
            <h1>
                Genre:
            </h1>
            <%= @genre.genre_name %><br />
            <h1>
                Description:
            </h1>
            <%= @genre.genre_description %><br />
            <h1>
                Items:
            </h1>

            <%= render 'item' %>
            
            <%= render 'form' %>
        </section>
    </aside>
</div>